### ISSUE TITLE
Google Drive Download Limitations

### ISSUE THREAD

**Issue by mikonvergence** [cloudsen12/cloudsen12#1]
I found Google Drive to be quite problematic for a dataset this large.

* It is too big to download the entire dataset directly via a web browser. On the other hand, `gdown` has many limitations, such as 50 files per call if a folder is to be downloaded.
* The `example01.ipynb` (https://cloudsen12.github.io/examples.html) shows how to download a single file at a time, but after a certain quantity of downloaded file, `gdown` will stop working reliably and throws permission errors (even though the same file can always be accessed through a web browser) https://github.com/wkentaro/gdown/issues/43 (in the case of CloudSEN12 the `&confirm=t` solution is not applicable).
* The issues with `gdown` occur both via bash as well as python interfaces of `gdown`

### My Solution
Instead of using `gdown`
```
gdown <file_id> -O <output_file_path>
```
the files can be downloaded without restrictions using `curl`:
```
curl -L -s -o <output_file_path> '<file_google_drive_link>'
```

where `<file_idx>` would be like `1I27sK2ET2RCUFs4idDDigIFAnCTMB-De`
and `<file_google_drive_link>` would be like `https://drive.google.com/uc?export=download&id=1I27sK2ET2RCUFs4idDDigIFAnCTMB-De`.

> For my specific case, I've written a script that retrieves information about all of the files that have not yet been acquired, and then passes them into a bash script that uses curl to download.

### Potential Improvement
Perhaps I have missed some easier way of acquiring the dataset for local use, but I found the process of getting the dataset quite cumbersome. I think it would be quite beneficial to consider other options apart from Google Drive.

Zenodo has size limitations as well (50GB per dataset I think), but perhaps CloudSEN12 could be split into parts that will fit that (such as based on sensing modality, label quality, cloud coverage, or geographic region)?

Ultimately, there should be a clear and a fast way for a new user to download the dataset in its entirety (or at least for a specific modality).

---
It does look like a really solid dataset for cloud detection, so thank you for sharing and putting all the work into it! :rocket:

**Comment by csaybar** [comment]
Hi @mikonvergence, sorry for the inconvenience, I'm going to upgrade the script soon to avoid this issue.  You can find cloudSEN12 dataset in this FTP: https://www.scidb.cn/en/detail?dataSetId=f72d622ff4ea4fa18070456a98222b1a.

**Comment by mikonvergence** [comment]
Thank you @csaybar, that makes sense. The FTP should do the job!
